test

diff --git a/general/package/hisilicon-osdrv-hi3516av100/files/script/load_hisilicon b/general/package/hisilicon-osdrv-hi3516av100/files/script/load_hisilicon
--- a/general/package/hisilicon-osdrv-hi3516av100/files/script/load_hisilicon
+++ b/general/package/hisilicon-osdrv-hi3516av100/files/script/load_hisilicon
@@ -20,6 +20,33 @@ report_error() {
         exit 1
 }
 
+insert_mmz() {
+        insmod mmz.ko mmz=anonymous,0,$mmz_start,$mmz_size anony=1 || report_error
+}
+
+insert_detect() {
+        cd /lib/modules/4.9.37/hisilicon
+        insert_mmz
+        insmod hi_media.ko
+        insmod hi3516a_base.ko
+        insmod hi3516a_sys.ko vi_vpss_online=$b_arg_online sensor=unknown mem_total=$mem_total
+        insert_isp
+        insmod sensor_i2c.ko
+        insmod sensor_spi.ko
+        SENSOR=ar0230 insert_sns
+}
+
+remove_detect() {
+        rmmod -w sensor_spi
+        rmmod -w sensor_i2c
+        rmmod -w hi3516a_isp
+        rmmod -w hi3516a_sys
+        rmmod -w hi3516a_base
+        rmmod -w hi_media
+        rmmod -w mmz
+        rmmod -w sys_config
+}
+
 insert_audio() {
         insmod acodec.ko
         insmod hi3516a_aio.ko
@@ -46,66 +73,67 @@ remove_sns() {
 }
 
 sys_config() {
+        # pinmux configuration
+        devmem 0x200f0000 32 0x1 # 0: GPIO0_5, 1: SENSOR_CLK
+        devmem 0x200f0004 32 0x1 # 1: FLASH_TRIG, 0: GPIO0_6, 2: SPI1_CSN1
+        devmem 0x200f0008 32 0x1 # 1: SHUTTER_TRIG, 0: GPIO0_7, 2: SPI1_CSN2
 
-		devmem 0x200f0070 32 0x1;		# i2c2_sda
-		devmem 0x200f0074 32 0x1;		# i2c2_scl
+        # clock configuration
+        devmem 0x20030030 32 0x00004005 # AVC-300M VGS-300M VPSS-250M VEDU-300M mda1axi 250M mda0axi 300M DDR-250
+        devmem 0x20030104 32 0x3        # VICAP-198M VPSS-198M
+        devmem 0x2003002c 32 0x90007    # VICAP-250M, ISP unreset & clk en, Sensor clk en-37.125M, clk reverse
+        #devmem 0x20030034 32 0xffc             # VDP-1080p@60fps unreset & clk en
+        #devmem 0x20030034 32 0xef74            # VDP-PAL/NTSC
+        devmem 0x20030040 32 0x2002 # VEDU0 AVC unreset & clk en
+        devmem 0x20030048 32 0x2    # VPSS0 unreset & clk en
 
-		devmem 0x200f0000 32 0x1		# 0: GPIO0_5, 		1: SENSOR_CLK
-		devmem 0x200f0004 32 0x1		# 1ЈєFLASH_TRIG,	0: GPIO0_6,		2ЈєSPI1_CSN1
-		devmem 0x200f0008 32 0x0		# 1ЈєSHUTTER_TRIG,	0ЈєGPIO0_7,		2ЈєSPI1_CSN2
-		
-		devmem 0x20030030 32 0x00004005      # AVC-300M VGS-300M VPSS-250M VEDU-300M mda1axi 250M mda0axi 300M DDR-250
-		devmem 0x20030104 32 0x3             # VICAP-198M VPSS-198M
-		devmem 0x2003002c 32 0x90007         # VICAP-250M, ISP unreset & clk en, Sensor clk en-37.125M, clk reverse
-		#devmem 0x20030034 32 0xffc           # VDP-1080p@60fps unreset & clk en
-		devmem 0x20030034 32 0xef74          #VDP-PAL/NTSC
-		devmem 0x20030040 32 0x2002          # VEDU0 AVC unreset & clk en
-		devmem 0x20030048 32 0x2             # VPSS0 unreset & clk en
+        devmem 0x20030058 32 0x2 # TDE unreset & clk en
+        devmem 0x2003005c 32 0x2 # VGS unreset & clk en
+        devmem 0x20030060 32 0x2 # JPGE  unreset & clk en
 
-		devmem 0x20030058 32 0x2             # TDE unreset & clk en
-		devmem 0x2003005c 32 0x2             # VGS unreset & clk en
-		devmem 0x20030060 32 0x2             # JPGE  unreset & clk en
+        devmem 0x20030068 32 0x2 # MDU unreset & clk en
+        devmem 0x2003006c 32 0x2 # IVE-300MHz unreset & clk en
+        #devmem 0x20030070 32 0x2       # VOIE unreset & clk en
 
-		devmem 0x20030068 32 0x2             # MDU unreset & clk en
-		devmem 0x2003006c 32 0x2             # IVE-300MHz unreset & clk en
-		#devmem 0x20030070 32 0x2            # VOIE unreset & clk en
+        devmem 0x2003007c 32 0x2 # cipher unreset & clk en
+        devmem 0x2003008c 32 0xe # aio MCLK PLL 1188M, unreset & clk en
+        #devmem 0x200300d8 32 0xa;      # ddrt
 
-		devmem 0x2003007c 32 0x2             # cipher unreset & clk en
-		devmem 0x2003008c 32 0xe             # aio MCLK PLL 1188M, unreset & clk en
-		#devmem 0x200300d8 32 0xa;           # ddrt
+        # system configuration
+        devmem 0x201200E0 32 0xd # internal codec:AIO MCLK out, CODEC AIO TX MCLK
 
-		# -------------vi vpss online open
-		if [ $b_arg_online -eq 1 ]; then
-			echo "==============vi_vpss_online==============";
-			devmem 0x20120004 32 0x40000000;			# online, SPI1 CS0
-			
-			#pri config
-			devmem 0x20120058 32 0x26666400			# each module 4bitЈєvedu       ddrt_md  ive  aio    jpge    tde   vicap  vdp
-			devmem 0x2012005c 32 0x66666103			# each module 4bitЈєsfc_nand   sfc_nor  nfc  sdio1  sdio0   a7    vpss   vgs 
-			devmem 0x20120060 32 0x66266666			# each module 4bitЈєreserve    reserve  avc  usb    cipher  dma2  dma1   gsf
-			
-			#timeout config                
-			devmem 0x20120064 32 0x00000011			# each module 4bitЈєvedu       ddrt_md  ive  aio    jpge    tde   vicap  vdp
-			devmem 0x20120068 32 0x00000020			# each module 4bitЈєsfc_nand   sfc_nor  nfc  sdio1  sdio0   a7    vpss   vgs 
-			devmem 0x2012006c 32 0x00000000			# each module 4bitЈєreserve    reserve  avc  usb    cipher  dma2  dma1   gsf 
-		else
-			echo "==============vi_vpss_offline==============";
-			devmem 0x20120004 32 0x0;			    # offline, mipi SPI1 CS0;
-			# pri config
-			devmem 0x20120058 32 0x26666401     		# each module 4bitЈєvedu       ddrt_md  ive  aio    jpge    tde   vicap  vdp
-			devmem 0x2012005c 32 0x66666112     		# each module 4bitЈєsfc_nand   sfc_nor  nfc  sdio1  sdio0   a7    vpss   vgs 
-			devmem 0x20120060 32 0x66266666    		# each module 4bitЈєreserve    reserve  avc  usb    cipher  dma2  dma1   gsf
-			# timeout config              		
-			devmem 0x20120064 32 0x00000011    		# each module 4bitЈєvedu       ddrt_md  ive  aio    jpge    tde   vicap  vdp
-			devmem 0x20120068 32 0x00000000    		# each module 4bitЈєsfc_nand   sfc_nor  nfc  sdio1  sdio0   a7    vpss   vgs 
-			devmem 0x2012006c 32 0x00000000    		# each module 4bitЈєreserve    reserve  avc  usb    cipher  dma2  dma1   gsf 
-		fi  
+        if [ $b_arg_online -eq 1 ]; then
+                # -------------vi vpss online
+                devmem 0x20120004 32 0x40000000 # online, SPI1 CS0
 
+                #pri config
+                devmem 0x20120058 32 0x26666400 # each module 4bit:vedu       ddrt_md  ive  aio    jpge    tde   vicap  vdp
+                devmem 0x2012005c 32 0x66666103 # each module 4bit:sfc_nand   sfc_nor  nfc  sdio1  sdio0   a7    vpss   vgs
+                devmem 0x20120060 32 0x66266666 # each module 4bit:reserve    reserve  avc  usb    cipher  dma2  dma1   gsf
 
-		# msic config
-		devmem 0x201200E0 32 0xd					# internal codecЈ¬AIO MCLK out, CODEC AIO TX MCLK 
-		#devmem 0x201200E0 32 0xe				# external codec: AIC31/AK7756Ј¬AIO MCLK out, CODEC AIO TX MCLK 
-		
+                #timeout config
+                devmem 0x20120064 32 0x00000011 # each module 4bit:vedu       ddrt_md  ive  aio    jpge    tde   vicap  vdp
+                devmem 0x20120068 32 0x00000020 # each module 4bit:sfc_nand   sfc_nor  nfc  sdio1  sdio0   a7    vpss   vgs
+                devmem 0x2012006c 32 0x00000000 # each module 4bit:reserve    reserve  avc  usb    cipher  dma2  dma1   gsf
+        else
+                devmem 0x20120004 32 0x0 # offline, mipi SPI1 CS0;
+                # pri config
+                devmem 0x20120058 32 0x26666401 # each module 4bit:vedu       ddrt_md  ive  aio    jpge    tde   vicap  vdp
+                devmem 0x2012005c 32 0x66666112 # each module 4bit:sfc_nand   sfc_nor  nfc  sdio1  sdio0   a7    vpss   vgs
+                devmem 0x20120060 32 0x66266666 # each module 4bit:reserve    reserve  avc  usb    cipher  dma2  dma1   gsf
+                # timeout config
+                devmem 0x20120064 32 0x00000011 # each module 4bit:vedu       ddrt_md  ive  aio    jpge    tde   vicap  vdp
+                devmem 0x20120068 32 0x00000000 # each module 4bit:sfc_nand   sfc_nor  nfc  sdio1  sdio0   a7    vpss   vgs
+                devmem 0x2012006c 32 0x00000000 # each module 4bit:reserve    reserve  avc  usb    cipher  dma2  dma1   gsf
+        fi
+}
+
+insert_isp() {
+        case $SENSOR in
+        *)
+                insmod hi3516a_isp.ko
+                ;;
+        esac
 }
 
 insert_sns() {
@@ -198,7 +226,7 @@ insert_sns() {
                 devmem 0x200f0050 32 0x2     # i2c0_scl
                 devmem 0x200f0054 32 0x2     # i2c0_sda
                 devmem 0x2003002c 32 0xE0007 # sensor unreset, clk 24MHz, VI 250MHz
-                devmem 0x20030104 32 0x0	 # VI 250MHz
+                devmem 0x20030104 32 0x0
                 ;;
         ar0230 | ar0237 | sc4236)
                 devmem 0x200f0050 32 0x2 # i2c0_scl
@@ -219,176 +247,87 @@ insert_sns() {
                 devmem 0x20030104 32 0x0     # Sensor 24M
                 ;;
         *)
-                echo "xxxx Invalid sensor type $SENSOR xxxx"
+                echo "xxxx Invalid sensor type $SNS_TYPE xxxx"
                 report_error
                 ;;
         esac
 
 }
-# insert_ko() {
-        # sys_config
+insert_ko() {
+        sys_config
 
-        # insmod mmz.ko mmz=anonymous,0,$mmz_start,$mmz_size anony=1 || report_error
+        insert_mmz
 
-        # insmod hi_media.ko
-        # insmod hi3516a_base.ko
+        insmod hi_media.ko
+        insmod hi3516a_base.ko
 
-        # insmod hi3516a_sys.ko vi_vpss_online=$b_arg_online sensor=$SENSOR mem_total=$mem_total || report_error
+        insmod hi3516a_sys.ko vi_vpss_online=$b_arg_online sensor=$SENSOR mem_total=$mem_total || report_error
 
-        # insmod hi3516a_tde.ko
-        # insmod hi3516a_region.ko
-        # insmod hi3516a_vgs.ko
+        insmod hi3516a_tde.ko
+        insmod hi3516a_region.ko
+        insmod hi3516a_vgs.ko
 
-        # insmod hi3516a_isp.ko
+        insert_isp
 
-        # insmod hi3516a_viu.ko detect_err_frame=10
-        # insmod hi3516a_vpss.ko rfr_frame_comp=1
-        # insmod hi3516a_vou.ko
-        # #insmod hi3516a_vou.ko transparentTransmit=1 #enable transparentTransmit
-        # #insmod hifb.ko video="hifb:vram0_size:1620"     # default pal
+        insmod hi3516a_viu.ko detect_err_frame=10
+        insmod hi3516a_vpss.ko rfr_frame_comp=1
+        insmod hi3516a_vou.ko
+        #insmod hi3516a_vou.ko transparentTransmit=1 #enable transparentTransmit
+        #insmod hifb.ko video="hifb:vram0_size:1620"     # default pal
 
-        # insmod hi3516a_rc.ko
-        # insmod hi3516a_venc.ko
-        # insmod hi3516a_chnl.ko #ChnlLowPower=1
-        # insmod hi3516a_h264e.ko H264eMiniBufMode=1
-        # insmod hi3516a_h265e.ko H265eMiniBufMode=1
-        # insmod hi3516a_jpege.ko
-        # #insmod hi3516a_ive.ko save_power=0
-        # #insmod hi3516a_ive.ko
+        insmod hi3516a_rc.ko
+        insmod hi3516a_venc.ko
+        insmod hi3516a_chnl.ko #ChnlLowPower=1
+        insmod hi3516a_h264e.ko H264eMiniBufMode=1
+        insmod hi3516a_h265e.ko H265eMiniBufMode=1
+        insmod hi3516a_jpege.ko
+        #insmod hi3516a_ive.ko save_power=0
+        #insmod hi3516a_ive.ko
 
-        # insmod sensor_i2c.ko
-        # insmod pwm.ko
-        # #insmod piris.ko
+        insmod sensor_i2c.ko
+        insmod pwm.ko
+        #insmod piris.ko
 
-        # insert_sns
-        # insert_audio
+        insert_sns
+        insert_audio
 
-        # insmod hi_mipi.ko
-        # insmod wdt.ko #nodeamon=1
-        # echo "==== Your input Sensor type is $SENSOR ===="
-# }
-
-# remove_ko() {
-        # rmmod -w wdt
-        # remove_audio
-        # remove_sns
-
-        # rmmod -w pwm
-        # #rmmod -w piris
-        # #rmmod -w hi3516a_ive
-
-        # rmmod -w hi3516a_rc
-        # rmmod -w hi3516a_jpege
-        # rmmod -w hi3516a_h265e
-        # rmmod -w hi3516a_h264e
-        # rmmod -w hi3516a_chnl
-        # rmmod -w hi3516a_venc
-
-        # #rmmod -w hifb
-        # rmmod -w hi3516a_vou
-        # rmmod -w hi3516a_vpss
-        # rmmod -w hi3516a_viu
-        # rmmod -w hi_mipi
-
-        # rmmod -w hi3516a_vgs
-        # rmmod -w hi3516a_region
-        # rmmod -w hi3516a_tde
-
-        # rmmod -w hi3516a_isp
-        # rmmod -w hi3516a_sys
-        # rmmod -w hi3516a_base
-        # rmmod -w hi_media
-        # rmmod -w mmz
-# }
-
-insert_ko()
-{
-	# sys config
-	sys_config;
- 
-	insmod mmz.ko mmz=anonymous,0,$mmz_start,$mmz_size anony=1 || report_error
-	insmod hi_media.ko
-	insmod hi3516a_base.ko
-	
-	insmod hi3516a_sys.ko vi_vpss_online=$b_arg_online sensor=$SENSOR
-
-	insmod hi3516a_tde.ko
-	insmod hi3516a_region.ko
-	insmod hi3516a_vgs.ko
-
-	insmod hi3516a_isp.ko
-	insmod hi3516a_viu.ko detect_err_frame=10;
-	insmod hi3516a_vpss.ko
-	insmod hi3516a_vou.ko #lowPowerMode=0
-	#insmod hi3516a_vou.ko detectCycle=0            #close dac detect
-	#insmod hifb.ko video="hifb:vram0_size:1620"     # default pal
-
-	insmod hi3516a_rc.ko
-	insmod hi3516a_venc.ko
-	insmod hi3516a_chnl.ko
-	insmod hi3516a_h264e.ko
-	insmod hi3516a_h265e.ko
-	insmod hi3516a_jpege.ko
-	insmod hi3516a_vda.ko
-	insmod hi3516a_ive.ko
-
-	insmod sensor_i2c.ko
-	insmod pwm.ko
-	insmod piris.ko
-	#insmod adv_7441.ko
-	#insmod sil9024.ko norm=12    #1080P@30fps
-
-	echo "==== Your input Sensor type is $SENSOR ===="
-	#insert_sns > /dev/null
-	insert_sns
-
-	insert_audio
-	echo "==== Your input Sensor type is $SENSOR ===="
-
-	insmod hi_mipi.ko
-	#insmod hi3516a_pm.ko
+        insmod hi_mipi.ko
+        insmod wdt.ko #nodeamon=1
+        echo "==== Your input Sensor type is $SENSOR ===="
 }
 
-remove_ko()
-{
-	#rmmod -w hi3516a_pm
-	remove_audio
-	remove_sns
+remove_ko() {
+        rmmod -w wdt
+        remove_audio
+        remove_sns
 
-	rmmod -w sil9024 &> /dev/null
-	rmmod -w sil9034 &> /dev/null
-	rmmod -w pwm	
+        rmmod -w pwm
+        #rmmod -w piris
+        #rmmod -w hi3516a_ive
 
-	rmmod -w hi3516a_ive
-	rmmod -w hi3516a_vda
-	
-	rmmod -w hi3516a_rc
-	rmmod -w hi3516a_jpege
-	rmmod -w hi3516a_h264e
-	rmmod -w hi3516a_h265e
-	rmmod -w hi3516a_chnl
-	rmmod -w hi3516a_venc
+        rmmod -w hi3516a_rc
+        rmmod -w hi3516a_jpege
+        rmmod -w hi3516a_h265e
+        rmmod -w hi3516a_h264e
+        rmmod -w hi3516a_chnl
+        rmmod -w hi3516a_venc
 
-	rmmod -w hifb
-	rmmod -w hi3516a_vou
-	rmmod -w hi3516a_vpss
-	rmmod -w hi3516a_viu
-	rmmod -w hi_mipi
+        #rmmod -w hifb
+        rmmod -w hi3516a_vou
+        rmmod -w hi3516a_vpss
+        rmmod -w hi3516a_viu
+        rmmod -w hi_mipi
 
-	rmmod -w ssp_ad9020
-	rmmod -w hi3516a_vgs
-	rmmod -w hi3516a_region
-	rmmod -w hi3516a_tde
+        rmmod -w hi3516a_vgs
+        rmmod -w hi3516a_region
+        rmmod -w hi3516a_tde
 
-	rmmod -w sensor_i2c
-	rmmod -w piris
-	rmmod -w hi3516a_isp
-	rmmod -w hi3516a_sys
-	rmmod -w hi3516a_base
-	rmmod -w hi_media
-	rmmod -w mmz
+        rmmod -w hi3516a_isp
+        rmmod -w hi3516a_sys
+        rmmod -w hi3516a_base
+        rmmod -w hi_media
+        rmmod -w mmz
 }
-
 
 load_usage()
 {
@@ -493,15 +432,40 @@ calc_mmz_info
 #######################Action###############################
 
 if [ $# -lt 1 ]; then
-    load_usage;
-    exit 0;
+        load_usage
+        exit 0
+fi
+
+# Sensor config
+# SENSOR=${SENSOR:=imx307}
+#
+
+if [ -n "$SENSOR" ]; then
+        logger -s -p daemon.info -t hisilicon "Manualy set SENSOR as ${SENSOR}"
+else
+        if fw_printenv -n sensor >/dev/null; then
+                SENSOR_ENV=$(fw_printenv -n sensor)
+                export SENSOR=${SENSOR_ENV}
+                logger -s -p daemon.info -t hisilicon "Get data from environment and set SENSOR as ${SENSOR}"
+        else
+                insert_detect
+                SENSOR_DETECT=$(ipcinfo --short-sensor)
+                export SENSOR=${SENSOR_DETECT:=unknown}
+                remove_detect
+                logger -s -p daemon.info -t hisilicon "Get data from ipcinfo and set SENSOR as ${SENSOR}"
+                fw_setenv sensor $SENSOR && logger -s -p daemon.info -t hisilicon "Write detected ${SENSOR} to U-Boot ENV"
+        fi
 fi
 
 if [ $b_arg_remove -eq 1 ]; then
-	remove_ko;
+        remove_ko
 fi
 
-if [ $b_arg_insmod -eq 1 ]; then
-	cd /lib/modules/4.9.37/hisilicon
-	insert_ko;
+if [ "$SENSOR" = "unknown" ]; then
+        exit 1
+else
+        if [ $b_arg_insmod -eq 1 ]; then
+                cd /lib/modules/4.9.37/hisilicon
+                insert_ko
+        fi
 fi
